function forward() end
function back() end
function up() end
function down() end
function turnLeft() end
function turnRight() end
function dig(side) end
function digUp(side) end
function digDown(side) end
function place() end
function placeUp() end
function placeDown() end
function drop(count) end
function select(slot) end
function getItemCount(slot) end
function getItemSpace(slot) end
function detect() end
function detectUp() end
function detectDown() end
function compare() end
function compareUp() end
function compareDown() end
function attack(side) end
function attackUp(side) end
function attackDown(side) end
function dropUp(count) end
function dropDown(count) end
function suck(count) end
function suckUp(count) end
function suckDown(count) end
function getFuelLevel() end
function refuel(count) end
function compareTo(slot) end
function transferTo(slot, count) end
function getSelectedSlot() end
function getFuelLimit() end
function equipLeft() end
function equipRight() end
function inspect() end
function inspectUp() end
function inspectDown() end
function getItemDetail(slot) end
