// SPDX-FileCopyrightText: 2022 The CC: Tweaked Developers
//
// SPDX-License-Identifier: MPL-2.0

package dan200.computercraft.gametest

import com.mojang.authlib.GameProfile
import dan200.computercraft.api.ComputerCraftAPI
import dan200.computercraft.gametest.api.Structures
import dan200.computercraft.gametest.api.assertCraftable
import dan200.computercraft.gametest.api.craftItem
import dan200.computercraft.gametest.api.immediate
import dan200.computercraft.impl.PocketUpgrades
import dan200.computercraft.impl.TurtleUpgrades
import dan200.computercraft.shared.ModRegistry
import dan200.computercraft.shared.integration.UpgradeRecipeGenerator
import dan200.computercraft.shared.recipe.CustomShapedRecipe
import dan200.computercraft.shared.recipe.CustomShapelessRecipe
import net.minecraft.gametest.framework.GameTest
import net.minecraft.gametest.framework.GameTestHelper
import net.minecraft.nbt.CompoundTag
import net.minecraft.nbt.NbtUtils
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.entity.player.Player
import net.minecraft.world.inventory.AbstractContainerMenu
import net.minecraft.world.inventory.MenuType
import net.minecraft.world.item.ItemStack
import net.minecraft.world.item.Items
import org.junit.jupiter.api.Assertions.assertEquals
import java.util.*

class Recipe_Test {
    /**
     * Test that crafting results contain NBT data.
     *
     * Mostly useful for Fabric, where we need a mixin for this.
     */
    @GameTest(template = Structures.DEFAULT)
    fun Craft_result_has_nbt(context: GameTestHelper) = context.immediate {
        val result = context.craftItem(
            ItemStack(Items.SKELETON_SKULL),
            ItemStack(ModRegistry.Items.COMPUTER_ADVANCED.get()),
        )

        val profile = GameProfile(UUID.fromString("f3c8d69b-0776-4512-8434-d1b2165909eb"), "dan200")

        val tag = CompoundTag()
        tag.put("SkullOwner", NbtUtils.writeGameProfile(CompoundTag(), profile))

        assertEquals(tag, result.tag, "Expected NBT tags to be the same")
    }

    /**
     * Test that all impostor recipes are craftable.
     */
    @GameTest(template = Structures.DEFAULT)
    fun Imposter_recipes_craftable(context: GameTestHelper) = context.immediate {
        // FIXME: Skip these recipes, as the NBT does not match.
        val skipRecipes = setOf(
            ResourceLocation(ComputerCraftAPI.MOD_ID, "printed_pages"),
            ResourceLocation(ComputerCraftAPI.MOD_ID, "printed_book"),
        )

        for (recipe in context.level.server.recipeManager.recipes) {
            if (recipe is CustomShapedRecipe || recipe is CustomShapelessRecipe) {
                context.assertCraftable(recipe, matchNbt = !skipRecipes.contains(recipe.id))
            }
        }
    }

    /**
     * Test that recipes generated by [UpgradeRecipeGenerator] are craftable.
     */
    @GameTest(template = Structures.DEFAULT)
    fun Upgrade_recipes_craftable(context: GameTestHelper) = context.immediate {
        val generator = UpgradeRecipeGenerator { it }

        fun checkUsage(message: String, size: Int, item: ItemStack) {
            val recipes = generator.findRecipesWithInput(item)
            assertEquals(size, recipes.size, message)

            for (recipe in recipes) {
                // Ensure the ingredient appears in the recipe.
                if (!recipe.ingredients.any { ItemStack.isSameItemSameTags(it.items[0], item) }) {
                    context.fail("Cannot find item ${item}${item.tag} in ${recipe.ingredients}")
                }

                // Ensure the recipe can actually be crafted using the main recipe manager.
                context.assertCraftable(recipe)
            }
        }

        // Speakers should be an input to 4 recipes (2xPocket, 2xTurtle).
        checkUsage("Usage: Speaker", 4, ItemStack(ModRegistry.Items.SPEAKER.get()))

        // Check recipes which can be crafted with a turtle
        checkUsage(
            "Usage: Turtle without upgrades",
            TurtleUpgrades.instance().upgrades.size * 2,
            ItemStack(ModRegistry.Items.TURTLE_NORMAL.get()),
        )
        checkUsage(
            "Usage: Turtle with one upgrade",
            TurtleUpgrades.instance().upgrades.size,
            ModRegistry.Items.TURTLE_NORMAL.get().create(
                -1,
                "",
                -1,
                TurtleUpgrades.instance().get(ItemStack(ModRegistry.Items.SPEAKER.get()))!!,
                null,
                0,
                null,
            ),
        )

        // Check recipes which can be crafted with a pocket computer
        checkUsage(
            "Usage: Pocket computer without upgrades",
            PocketUpgrades.instance().upgrades.size,
            ItemStack(ModRegistry.Items.POCKET_COMPUTER_NORMAL.get()),
        )

        fun checkRecipe(message: String, size: Int, item: ItemStack) {
            val recipes = generator.findRecipesWithOutput(item)
            assertEquals(size, recipes.size, message)

            for (recipe in recipes) {
                // Ensure the result matches the input.
                val result = recipe.getResultItem(context.level.registryAccess())
                if (!ItemStack.isSameItemSameTags(result, item) || result.count != item.count) {
                    context.fail("Expected to craft ${item}${item.tag} but crafted ${result}${result.tag}")
                }

                // Ensure the recipe can actually be crafted using the main recipe manager.
                context.assertCraftable(recipe)
            }
        }

        // Check recipes which craft a turtle
        checkRecipe(
            "Recipe: Turtle with one upgrade",
            1,
            ModRegistry.Items.TURTLE_NORMAL.get().create(
                -1,
                "",
                -1,
                TurtleUpgrades.instance().get(ItemStack(ModRegistry.Items.SPEAKER.get()))!!,
                null,
                0,
                null,
            ),
        )
        checkRecipe(
            "Recipe: Turtle with two upgrades",
            2,
            ModRegistry.Items.TURTLE_NORMAL.get().create(
                -1,
                "",
                -1,
                TurtleUpgrades.instance().get(ItemStack(ModRegistry.Items.SPEAKER.get()))!!,
                TurtleUpgrades.instance().get(ItemStack(ModRegistry.Items.WIRELESS_MODEM_NORMAL.get()))!!,
                0,
                null,
            ),
        )

        // Check recipes which craft a pocket computer
        checkRecipe(
            "Recipe: Pocket computer with one upgrade",
            1,
            ModRegistry.Items.POCKET_COMPUTER_NORMAL.get().create(
                -1,
                "",
                -1,
                PocketUpgrades.instance().get(ItemStack(ModRegistry.Items.SPEAKER.get()))!!,
            ),
        )
    }

    object DummyMenu : AbstractContainerMenu(MenuType.GENERIC_9x1, 0) {
        override fun quickMoveStack(player: Player, slot: Int): ItemStack = ItemStack.EMPTY
        override fun stillValid(p0: Player): Boolean = true
    }
}
