# SPDX-FileCopyrightText: 2021 The CC: Tweaked Developers
#
# SPDX-License-Identifier: MPL-2.0

modLoader="javafml"
loaderVersion="[30,)"

issueTrackerURL="https://github.com/cc-tweaked/CC-Tweaked/issues"
displayURL="https://github.com/cc-tweaked/CC-Tweaked"

credits="Created by Daniel Ratcliffe (@DanTwoHundred)"
authors="Daniel Ratcliffe, Aaron Mills, SquidDev"
license="ComputerCraft Public License (https://raw.githubusercontent.com/dan200/ComputerCraft/master/LICENSE)"

[[mods]]
modId="cctest"
version="1.0.0"
displayName="CC: Tweaked test framework"
description='''
A test framework for ensuring CC: Tweaked works correctly.
'''

[[dependencies.cctest]]
modId="computercraft"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
