// SPDX-FileCopyrightText: 2026 The CC: Tweaked Developers
//
// SPDX-License-Identifier: MPL-2.0

package cc.tweaked.gradle

import cc.tweaked.vanillaextract.core.util.MoreFiles
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.FileTree
import org.gradle.api.problems.*
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.compile.JavaCompile
import org.gradle.work.InputChanges
import java.io.File
import javax.inject.Inject

/**
 * Compile Java sources, then verify the resulting classes are identical to another set of files.
 *
 * This is used to ensure our common sources compile cleanly against Forge/Fabric directly.
 */
abstract class VerifyJavaCompile : JavaCompile() {
    /**
     * The directories containing the classes to compare against.
     */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val referenceDirectories: ConfigurableFileCollection

    /**
     * Files to exclude from verification.
     */
    @get:Input
    abstract val ignoredFiles: SetProperty<String>

    @get:Inject
    abstract val problems: Problems

    override fun compile(inputs: InputChanges) {
        super.compile(inputs)

        val reporter = problems.reporter

        val referenceFiles = readFiles(reporter, referenceDirectories.asFileTree)
        val outputFiles = readFiles(reporter, destinationDirectory.asFileTree)
        val ignored = ignoredFiles.get().toMutableSet()

        val problems = mutableListOf<Problem>()

        // Check all output files match
        for ((path, outputFile) in outputFiles) {
            val referenceFile = referenceFiles[path]
            if (referenceFile == null) {
                val problem = reporter.create(EXTRA_FILE) {
                    contextualLabel("'$path' is generated by this task, but is not in the reference classes")
                    fileLocation(outputFile.file.toString())
                }
                if (ignored.remove(path)) {
                    reporter.report(problem)
                } else {
                    problems.add(problem)
                }
            } else if (outputFile.hash != referenceFile.hash) {
                val problem = reporter.create(MISMATCH) {
                    contextualLabel("'$path' has different file contents'")
                    fileLocation(outputFile.file.toString())
                    fileLocation(referenceFile.file.toString())
                }
                if (ignored.remove(path)) {
                    reporter.report(problem)
                } else {
                    problems.add(problem)
                }
            }
        }

        // Check we've got no additional reference files.
        for ((path, referenceFile) in referenceFiles) {
            if (outputFiles.containsKey(path)) continue

            val problem = reporter.create(MISSING_FILE) {
                contextualLabel("'$path' is in the reference classes but not generated by this task")
                fileLocation(referenceFile.file.toString())
            }
            if (ignored.remove(path)) {
                reporter.report(problem)
            } else {
                problems.add(problem)
            }
        }

        // Ensure there's no redundant ignored files.
        if (ignored.isNotEmpty()) {
            val problem = reporter.create(REDUNDANT_IGNORE) {
                val files = ignored.sorted().joinToString(", ")
                details("$files are marked as excluded but had no problems")
            }
            problems.add(problem)
        }

        if (problems.isNotEmpty()) throw reporter.throwing(GradleException("Classes do not match"), problems)
    }

    private fun readFiles(reporter: ProblemReporter, dir: FileTree): Map<String, ClassFile> {
        val output = mutableMapOf<String, ClassFile>()
        dir.visit {
            if (isDirectory) return@visit

            val relativePath = path
            val hash = MoreFiles.computeSha1(file.toPath())

            if (output.putIfAbsent(relativePath, ClassFile(hash, file.absoluteFile)) != null) {
                throw reporter.throwing(GradleException("Multiple directories contain $relativePath"), DUPLICATE_FILE) {
                    fileLocation(file.absolutePath)
                }
            }
        }

        return output
    }

    class ClassFile(val hash: String, val file: File)

    companion object {
        private val GROUP: ProblemGroup = ProblemGroup.create("cc.tweaked.verify-java", "Verify Java")
        private val DUPLICATE_FILE: ProblemId = ProblemId.create("duplicate-file", "Duplicate file", GROUP)
        private val EXTRA_FILE: ProblemId = ProblemId.create("extra-file", "Additional file in output", GROUP)
        private val MISSING_FILE: ProblemId = ProblemId.create("missing-file", "Additional file in reference", GROUP)
        private val MISMATCH: ProblemId = ProblemId.create("mismatch", "Classes do not match", GROUP)
        private val REDUNDANT_IGNORE: ProblemId =
            ProblemId.create("redundant-ignore", "Ignored files entries without problems", GROUP)
    }
}
