image:
  file: config/gitpod/Dockerfile

ports:
  - port: 25565
    onOpen: notify

vscode:
  extensions:
    - eamodio.gitlens
    - github.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - redhat.java
    - richardwillis.vscode-gradle
    - vscjava.vscode-java-debug
    - vscode.github

tasks:
  - name: Setup pre-commit hool
    init: pre-commit install --config config/pre-commit/config.yml --allow-missing-config
  - name: Install npm packages
    init: npm ci
