describe("The fs library", function()
    describe("fs.complete", function()
        it("validates arguments", function()
            fs.complete("", "")
            fs.complete("", "", true)
            fs.complete("", "", nil, true)

            expect.error(fs.complete, nil):eq("bad argument #1 (expected string, got nil)")
            expect.error(fs.complete, "", nil):eq("bad argument #2 (expected string, got nil)")
            expect.error(fs.complete, "", "", 1):eq("bad argument #3 (expected boolean, got number)")
            expect.error(fs.complete, "", "", true, 1):eq("bad argument #4 (expected boolean, got number)")
        end)
    end)
end)
