describe("The term library", function()
    describe("term.redirect", function()
        it("validates arguments", function()
            expect.error(term.redirect, nil):eq("bad argument #1 (expected table, got nil)")
        end)

        it("prevents redirecting to term", function()
            expect.error(term.redirect, term)
                  :eq("term is not a recommended redirect target, try term.current() instead")
        end)
    end)

    describe("term.getLine", function()
        it("validates arguments", function()
            local _, y = term.getSize()
            expect.error(term.getLine, nil):eq("bad argument #1 (expected number, got nil)")
            expect.error(term.getLine, 0):eq("Line is out of range.")
            expect.error(term.getLine, y + 1):eq("Line is out of range.")
        end)
    end)
end)
