# SPDX-FileCopyrightText: 2023 The CC: Tweaked Developers
#
# SPDX-License-Identifier: MPL-2.0

[versions]
forge = "1.4.7-6.6.2.534"

jspecify = "1.0.0"
netty = "4.1.119.Final"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
netty-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }

[bundles]
netty = ["netty-codec", "netty-http"]

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.19.0" }
voldeloom = { id = "agency.highlysuspect.voldeloom", version = "2.4-SNAPSHOT" }
