name: Bug report
description: Report some misbehaviour in the mod
labels: [ bug ]
body:
- type: dropdown
  id: mc-version
  attributes:
    label: Minecraft Version
    description: What version of Minecraft are you using?
    options:
      - 1.20.1
      - 1.21.x
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    description: "What version of CC: Tweaked are you using?"
    placeholder: "e.g. 1.96.0"
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: Details
    description: |
      Description of the bug. Please include the following:
      - Logs: These will be located in the `logs/` directory of your Minecraft
        instance. Please upload them as a gist or directly into this editor.
      - Detailed reproduction steps: sometimes I can spot a bug pretty easily,
        but often it's much more obscure. The more information I have to help
        reproduce it, the quicker it'll get fixed.
