describe("image.nft", function()
    local nft = require("image.nft")

    describe("parse", function()
        it("validates arguments", function()
            nft.parse("")
            expect.error(nft.parse, nil):eq("bad argument #1 (expected string, got nil)")
        end)
    end)

    describe("load", function()
        it("validates arguments", function()
            nft.load("")
            expect.error(nft.load, nil):eq("bad argument #1 (expected string, got nil)")
        end)
    end)

    describe("draw", function()
        it("validates arguments", function()
            expect.error(nft.draw, nil):eq("bad argument #1 (expected table, got nil)")
            expect.error(nft.draw, {}, nil):eq("bad argument #2 (expected number, got nil)")
            expect.error(nft.draw, {}, 1, nil):eq("bad argument #3 (expected number, got nil)")
        end)
    end)
end)
